import type { Metadata } from "next";
import { Geist, Geist_Mono, Caveat } from "next/font/google";
import "./globals.css";
import MainDashboard from "@/components/main";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const caveat = Caveat({ subsets: ["latin"], variable: "--font-caveat" });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MainDashboard>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${caveat.className} antialiased`}
        >
          {children}
        </body>
      </html>
    </MainDashboard>
  );
}
